#UrsulaGIS
#Tue Jul 07 11:17:38 ART 2026
CultivoDefault=Maiz P
corrimientoPesada=0
OrdenPulv.PRODUCTOR=Su S.A.
OrdenSiembra.ING=Su Ing.
DOSIS_UNIDAD_KEY=pla10MtLineal
kgSemHa=kgSemHa
SEMILLA_DEFAULT=DM 46i20 25/26
CORRECCION_FLOW_TO_RINDE=false
Kg_FertHa=Fert L
cantMaxGeometriasSuperpuestas=50
metrosPorUnidadDistancia=1
Distancia=distance
Rendimient=flow
FECHA_KEY=01/10/2025
anchoFiltroOutlayers=50
LOCALE_KEY=es
OrdenFert.CULTIVO=Trigo 26/27
OrdenPulv.DESCRIPCION=108lts de Dino marca Dino
OrdenSiembra.ESTABLECIMIENTO=Regalada
OrdenFert.PRODUCTOR=Su S.A.
MARGEN=MARGEN
correccionSuperposicion=false
Prof_Nap=Prof_Nap
CANTIDAD_DISTANCIAS_ENTRADA_REGIMEN_PASADA=0
FERT_INSUMO_UNIDAD_KEY=Tn
Chat.DEEPSEEK_API_KEY=
costoLaborSiembra=50
OrdenPulv.CULTIVO=Trigo
RESUMIR_GEOMETRIAS=false
VOYAGER2_LICENSE_KEY=1C675C9A-93C4-469A-8248-91E27587733A
Densidad=Densidad
SUP_MINIMA_M2=0,00
correccionOutlayers=false
OrdenFert.ESTABLECIMIENTO=Su Establecimiento
LAST_FILE=
PPM_N=PPM_N
PPM_P=PPM_P
OrdenPulv.ING=Andres olivares
OrdenSiembra.CULTIVO=Trigo 26/27
gov.nasa.worldwind.avkey.InitialLongitude=-62.10291014744172
MAX_RINDE=20
PPM_K=PPM_K
IMP_PULV=IMP_PULV
COSTO_COSECHA_HA=1
correccionDemoraPesada=false
INSUMO_UNIDAD_KEY=Kg
OrdenSiembra.PRODUCTOR=Jagueles S.A.
Precio\ labor/Ha=34,4
LAST_DATE=31/03/2026
FERTILIZANTE_DEFAULT=Fosfato monoamónico
PRECIO_INSUMO=4,49
IMP_SIEM=IMP_SIEM
ANCHO_DEFAULT=8,32
PPM_S=PPM_S
VOYAGER2_NATIVE_LIB_PATH=
OrdenFert.ING=Horacio Tardini
Humedad=Moisture_s
COSTO_FIJO_KEY=0
OrdenSiembra.Nro=97
OrdenFert.Nro=57
CANTIDAD_DISTANCIAS_TOLERANCIA=5
costoLaborPulverizacion=37,71
RENTA=MARGEN
VOYAGER2_SDK_PATH=
OrdenPulv.Nro=4
OrdenSiembra.Unidad=Sem10m
N_VARIANZAS_TOLERA2=1
anchoGrilla=10,00
OrdenPulv.CONTRATISTA=Su Contratista
Dosis=Dosis
IMP_FERT=IMP_FERT
gov.nasa.worldwind.avkey.InitialAltitude=64000
NDVI_DOWNLOAD_TYPE(SR/TOA)=TOA
UuidTarjeta=
gov.nasa.worldwind.avkey.InitialLatitude=-34.012279080592066
COSTO_TN_KEY=0
OrdenCos.Nro=14
MAX_DATES_PER_QUERY=4
PREFERED_TREE_WIDTH=287,33
IMP_FIJO=IMP_FIJO
correccionAncho=false
ConvertirElevacionPiesAMetros=true
PORC_MO=PORC_MO
precioGrano=180
COSTO_T=COSTO_T
OrdenPulv.ESTABLECIMIENTO=Su Establecimiento
IMP_COSECH=IMP_COSECH
costoLaborFertilizacion=2
TOLERANCIA_CV_0_1=0.0
OrdenFert.DESCRIPCION=Fertilizacion incorporada urea trigo 2627 jag 22 100kg/ha
Elevacion=Ninguna
OrdenFert.CONTRATISTA=Su Contratista
DAH.PROJECT_URL_KEY=
OrdenSiembra.DESCRIPCION=Siembra fertilizada Trigo 26/27 Baguette 620\:147kg/ha MAP\:79kg/ha\nRegalada Lomas y brasito
COSTO_COSECHA_TN=1
MIN_RINDE=0
CALIBRAR_RINDE=true
CLASIFICADOR=Desvio Standar
OrdenSiembra.CONTRATISTA=Su Contratista
correccionRindeArea=false
USER=
Precio\ Kg\ Fert=0.8
Curso(deg)=headding
Agua_Pe=Agua_Pe
COSTO_FLETE_KEY=0
NUMERO_CLASES_CLASIFICACION=9
ENTRE_SURCO_DEFAULT=0,42
CORRECCION_COSECHA=100
Ancho=width
PrecioSemilla=6.25
correccionDistancia=false
