name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Explicitly request permissions for creating releases
permissions:
  contents: write
  packages: write

env:
  PRIMARY_BUNDLE_ID: com.ursulagis.desktop.JFXMain
  APP_VERSION: 1.0.${{ github.run_number }}
jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
      
      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix
      
      - name: Add Wix to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11 with JavaFX
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'
      
      - name: Build Windows Installer with Maven
        run: mvn -B clean install --file pom.xml
        env:
          # Activate Windows-specific profile
          MAVEN_OPTS: "-Dos.detected.name=windows"
      
      - name: List build artifacts
        run: |
          echo "Build artifacts in target directory:"
          dir target
          echo "MSI files:"
          dir target\*.msi
      
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: UrsulaGIS-Desktop_Zulu-${{ env.APP_VERSION }}_Win_x64_Installer
          path: target/*.msi
          retention-days: 30
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: UrsulaGIS-Desktop_Zulu_Win_x64_Installer-${{ env.APP_VERSION }}
          name: Windows Installer Build -${{ env.APP_VERSION }}
          body: |
            Windows MSI installer built from commit ${{ github.sha }}
            
            **Build Info:**
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Run: ${{ github.run_number }}
            - Date: ${{ github.event.head_commit.timestamp }}
          files: |
            target/*.msi
          prerelease: true
          draft: false
