name: Build Windows Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Explicitly request permissions for creating releases
permissions:
  contents: write
  packages: write

env:
  PRIMARY_BUNDLE_ID: com.ursulagis.desktop.JFXMain

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
      
      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix
      
      - name: Add Wix to Path
        run: echo "$HOME/target/wix" >> $GITHUB_PATH
      
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 24 with JavaFX
        uses: actions/setup-java@v4
        with:
          java-version: 24.0.2
          distribution: 'liberica'
          java-package: jdk+fx
          cache: 'maven'
      
      - name: Get Maven version
        id: maven-version
        run: |
          $version = mvn help:evaluate -Dexpression=project.version -q -DforceStdout
          $artifact = mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout
          $name = mvn help:evaluate -Dexpression=project.name -q -DforceStdout
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "artifact=$artifact" >> $env:GITHUB_OUTPUT
          echo "name=$name" >> $env:GITHUB_OUTPUT
      
      - name: Build Windows Installer with Maven
        run: mvn -B clean install --file pom.xml
        env:
          # Activate Windows-specific profile
          MAVEN_OPTS: "-Dos.detected.name=windows"
      
      - name: List build artifacts
        run: |
          echo "Build artifacts in target directory:"
          dir target
          echo "MSI files:"
          dir target\*.msi
      
      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.maven-version.outputs.artifact }}-${{ steps.maven-version.outputs.version }}.${{ github.run_number }}-Win_x64_Installer
          path: target/*.msi
          retention-days: 30
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          tag_name: ${{ steps.maven-version.outputs.artifact }}-Win_x64_Installer-${{ steps.maven-version.outputs.version }}.${{ github.run_number }}
          name: ${{ steps.maven-version.outputs.name }} Windows Installer v${{ steps.maven-version.outputs.version }}.${{ github.run_number }}
          body: |
            Windows MSI installer built from commit ${{ github.sha }}
            
            **Build Info:**
            - Version: ${{ steps.maven-version.outputs.version }}.${{ github.run_number }}
            - Artifact: ${{ steps.maven-version.outputs.artifact }}
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref_name }}
            - Run: ${{ github.run_number }}
            - Date: ${{ github.event.head_commit.timestamp }}
          files: |
            target/*.msi
          prerelease: true
          draft: false
