# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-package com.ursulagis.desktop.guides/building-and-testing-java-with-maven

name: Maven Basic Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'liberica'
        java-package: jdk+fx
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
